### ISSUE TITLE
Get a moonbeam maintainer and verify all the steps have been done.

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/hmt-escrow#305]
Moonbeam has already had a good deal of work done for it

https://github.com/humanprotocol/hmt-escrow/pull/250
https://github.com/humanprotocol/hmt-escrow/pull/246
https://github.com/humanprotocol/hmt-escrow/commit/ee415369e7516cdacbd148e2036526d8f0417b16

Please review and build on these first.

HMT-Escrow supports arbitrary EVM networks but there's a bit of work to do to make a network first class and make sure that it works. All of our EVM network launches are supported by gitcoin but you can gain a yearly bonus by being our network sponsor. 

### Steps to receive gitcoin bounty
* [x] Launch the contracts on the devnet and make sure that everything is working
* [ ] Launch contracts on production network and file a commit with all the contract information to this repo's documentation. Here's an example https://github.com/humanprotocol/hmt-escrow/pull/296
* [ ] Launch KVstore contracts https://github.com/humanprotocol/eth-kvstore
* [ ] Add the contracts to the relevant network scanner (etherscan equivalent) 
* [ ] Launch a working app on the network. The easiest one to get going is our example fortune. https://github.com/humanprotocol/fortune  Make a video of the functionality of the app working on the new network and link to relevant scanner transactions.
* [ ] Add to human dashboard [ https://dashboard.humanprotocol.org/ ]
* [ ] Request to become the maintainer for your EVM network. We will list you on our repo, give you an extra reward (generally around 1 ETH per year) and invite you to conferences. We will celebrate your name forever!
* [ ] Verify bridging of tokens works
### High level rules to make sure that you are doing this correctly
* [ ] We never want to create a mintable token. Your change should not change the total token supply from 1 billion

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200560623420491/1202080314416581) by [Unito](https://www.unito.io)

**Comment by posix4e** [comment]
The contract has already been launched, and it’s already on the scanner, so just verify things.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1.0 ETH (3263.35 USD @ $3263.35/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/humanprotocol/hmt-escrow/305/100028709).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/humanprotocol/hmt-escrow/305/100028709).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $5,009,162.19 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 264 years, 7 months from now.
Please review their action plans below:


**1) [kaselunt](https://gitcoin.co/kaselunt) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/humanprotocol/hmt-escrow/305/100028709?mutate_worker_action=approve&worker=kaselunt) | [reject worker](https://gitcoin.co/issue/humanprotocol/hmt-escrow/305/100028709?mutate_worker_action=reject&worker=kaselunt))_.**

1. Use docker to spin up a moonbeam development node for local testing
2. Ensure moonbeam environment details are correct in truffle
3. Deploy contracts in local moonbeam environment, run tests to ensure everything is running as intended
4. Deploy contracts onto moonbeam mainnet, and again test everything. Write new unit / integration tests if necessary
5. Publish and verify the contracts to moonscan.io
6. Commit the contract details into the README
7. Deploy the fortune app in development environment and then mainnet, verify and publish contract
8. Make a video showing the app working as intended and provide links to the transactions on moonscan.io
9. Add to the human dashboard
10. Maintain the moonbeam network and start looking for the next human protocol bounty to work on!

I've just finished deploying my own (test) contracts across several chains and would love to get involved with the human protocol.
 
Thanks a lot! 
- Kase

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/humanprotocol/hmt-escrow/305/100028709).

**Comment by posix4e** [comment]
@kaselunt if you need support please join tech-discussions on the human protocol discord at hmt.ai

**Comment by kaseLunt** [comment]
Great, getting started on it now! Appreciate it

**Comment by developerfred** [comment]
@posix4e if this issue is available i would like to work on it

**Comment by kaseLunt** [comment]
The contracts have been deployed and verified on moonscan:

Verifying EscrowFactory
Pass - Verified:

https://moonbase.moonscan.io/address/0xeD26cc8A4eC4ade08BC7bc53951af9146F52347F#code

Verifying HMToken
Pass - Verified:

https://moonbase.moonscan.io/address/0xB1CD56218Dbc475360A454F71d870d844c6bD4E5#code

Verifying Migrations
Pass - Verified:

https://moonbase.moonscan.io/address/0xC911825fB431fF7eEEAe9F95fb626346B0a68ce1#code

I am now working on deploying the fortune dApp.
I have a few questions before deploying them to moonbeam live network

**Comment by Human-Protocol** [comment]
Sure 
if you need support please join tech-discussions on the human protocol discord at hmt.ai

**Comment by Human-Protocol** [comment]
This looks good for step

**Comment by posix4e** [comment]
When deploying production contracts use a dedicated wallet with a seed phrase you don't use anywhere else. You might be required to share it with us.

**Comment by kaseLunt** [comment]
Here are the verified contracts on moonbeam main net:

EscrowFactory
Pass - Verified:
https://moonbeam.moonscan.io/address/0x3C5a2966A1b5eBF9f4b2B372857C4deD545Bed45#code

HMToken
Pass - Verified:
https://moonbeam.moonscan.io/address/0xa1d4836243DfA3259e28b8A9D11377455B935632#code

Migrations
Pass - Verified:
https://moonbeam.moonscan.io/address/0xb096Eb12D0EadD73283F802dFF35D26F85Ed260d#code

KVStore
Pass - Verified:
https://moonbeam.moonscan.io/address/0xc1e779e71e6bf7ded0dddcb6e221404f497cee8e#code

**Comment by kaseLunt** [comment]
Here are the verified contracts on moonbeam main net:

EscrowFactory
Pass - Verified:
https://moonbeam.moonscan.io/address/0x3C5a2966A1b5eBF9f4b2B372857C4deD545Bed45#code

HMToken
Pass - Verified:
https://moonbeam.moonscan.io/address/0xa1d4836243DfA3259e28b8A9D11377455B935632#code

Migrations
Pass - Verified:
https://moonbeam.moonscan.io/address/0xb096Eb12D0EadD73283F802dFF35D26F85Ed260d#code

KVStore
Pass - Verified:
https://moonbeam.moonscan.io/address/0xc1e779e71e6bf7ded0dddcb6e221404f497cee8e#code

I have them on a fresh, dedicated wallet which I funded with GLMR for the deployments.

**Comment by kaseLunt** [comment]
deployment details have been added to documentation:
https://github.com/humanprotocol/hmt-escrow/pull/313

escrow dashboard now properly supports moonbeam and moonbase:
https://streamable.com/06d0w5
https://github.com/humanprotocol/escrow-dashboard/pull/4

**Comment by Human-Protocol** [comment]
@kaseLunt can you confirm the token is not mintable?

**Comment by Human-Protocol** [comment]
Sorry for the delay

**Comment by vkomodey** [comment]
Token Supply equals to 10**18. It is mintable

**Comment by Human-Protocol** [comment]
@kaseLunt I'm sorry we have to reject this until it's made non mintable

**Comment by posix4e** [comment]
Perhaps we can just burn the existing tokens?

**Comment by vkomodey** [comment]
Burning tokens mean the total supply will be equal to 0. It means, the token itself(HMT) can't be used if there is no "increase supply" thing present. Basically this "increase supply" represents a deposit action(a good example is a Polygon HMT analogue)

**Comment by posix4e** [comment]
This is stale, so we are going to stop work til we see more activity

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 264 years, 6 months from now.
Please review their action plans below:


**1) [menezesphill](https://gitcoin.co/menezesphill) has been approved to start work.**

Hi! I am ready to start working on this bounty. I plan to:

1) Deploy: Escrow Factory, KVStore, and HMToken contracts to Moonbase Alpha;
2) Ensure all units are working correctly;
3) Deploy: Escrow Factory, KVStore, and HMToken contracts to Moonbeam;
4) Verify contracts on https://moonbase.moonscan.io/ and https://moonscan.io/;
5) File a commit on https://github.com/humanprotocol/hmt-escrow/pull/296 with the contract addresses;
6) Add the Escrow Contract to the Human Dashboard by creating a PR to https://github.com/humanprotocol/escrow-dashboard;
7) Bridge tokens over to Moonbeam;
8) Launch an app based on https://github.com/humanprotocol/fortune, and create a video;
9) Request to become the maintainer of HMT on Moonbeam;
10) Get my name celebrated forever!!!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/humanprotocol/hmt-escrow/305/100028709).

**Comment by tnkerer** [comment]
Thanks for the approval. I have been following this issue since its publishing on GitCoin. I will try to pick it up from where Kase left it, but since I don't have access to the wallet that deployed the smart contracts, I believe I will have to redeploy all contracts.

**Comment by posix4e** [comment]
@menezesphill id recommend the first thing you work on is bridging existing tokens from ethereum to moonbeam

**Comment by posix4e** [comment]
@menezesphill wanna grab time to chat about.me/posix4e

**Comment by tnkerer** [comment]
> @menezesphill wanna grab time to chat about.me/posix4e

Great, I wanted to discuss a few options for bridging Hmt tokens to different networks.

**Comment by tnkerer** [comment]
Good afternoon team! I just dropped by to give a heads up about bridging HMT to Moonbeam. Here is some information I was able to gather from my interaction with their engineers:

____________________________________________________________________________
**Nomad:** Nomad is an already established solution for bridging from Ethereum to Moonbeam and is recommended by Moonbeam's engineers. I am in contact with Nomad's team to understand the minimum requirements for using their solution.

https://app.nomad.xyz/

**Pros:** Ready to use, recommended by Moonbeam, cheaper than AnySwap;
**Cons:** Transaction validation is not entirely decentralized. It depends on a small group of individuals both from Nomad and Moonbeam teams;
____________________________________________________________________________
**AnySwap**:  AnySwap is an already established and trusted solution for cross-chain bridging. It already supports Moonbeam mainet.

https://anyswap.exchange/#/router

**Pros:** Ready to use, trusted by the community;
**Cons:** Transaction validation is not entirely decentralized. It depends on five relayers maintained by both AnySwap and Slow Mist;
____________________________________________________________________________
**ChainBridge**: ChainBridge cross-chain solution is currently available on the test net (Rinkeby/Kovan-> Moonbase Alpha). However, to extend it to the mainet, the network needs Relayers (Decentralized agents that have to vote and accept cross-chain swap events).  

Currently, MoonBeam's team has no timeline for releasing ChainBridge on the main net, so I am trying to reach out to ChainSafe's engineers to figure out the complexity of setting up new Relayers for Moonbeam.

https://docs.moonbeam.network/builders/integrations/bridges/chainbridge/
____________________________________________________________________________
**Portales**: In parallel to that, after some conversation with Moonbeam engineers, my team has decided to participate in Moonriver's Hackathon to showcase our authorial bridge solution. If you guys want to read more about it, you can check out our repo, where most of the work will be available and open-sourced:

https://github.com/metamathstudios/portales-by-metamath/issues/1
https://github.com/orgs/metamathstudios/projects/1/views/1

**Comment by posix4e** [comment]
amazing work. All look like good options

**Comment by posix4e** [comment]
@menezesphill any updates?

**Comment by tnkerer** [comment]
@posix4e our bridge on Multichain is online! This week will have more updates about the non-bridge-related tasks! 😁

**Comment by tnkerer** [comment]
> @menezesphill any updates?

Hi @posix4e, have a few updates for this issue. Relevant documentation is [here](https://github.com/menezesphill/hmt-moonbeam). I just need a few HMT tokens on Ethereum mainet to proceed with bridge testing (Multichain minimum for HMT swaps is 50 HMT) and then I will be ready to prepare my PRs for this repo readme file and to [escrow-dashboard](https://github.com/humanprotocol/escrow-dashboard).

**Comment by tnkerer** [comment]
@posix4e updating what has been done so far:

**Task 1: Launch the contracts on the devnet and make sure that everything is working**

Relevant documentation is available [here](https://github.com/menezesphill/hmt-moonbeam#-deployed-smart-contract-addresses-on-moonbeam). 
____________________________________________________________________________
**Task 2: Launch contracts on production network and file a commit with all the contract information to this repo's documentation**

PR #326 submitted for review
____________________________________________________________________________
**Task 3: Launch KVstore contracts**

Relevant documentation is available [here](https://github.com/menezesphill/hmt-moonbeam#-deployed-smart-contract-addresses-on-moonbeam). 
____________________________________________________________________________
**Task 4: Add the contracts to the relevant network scanner**

Verified contract addresses on [moonscan.io](https://moonbeam.moonscan.io/)

[Escrow Factory on Moonbeam](https://moonbeam.moonscan.io/address/0x98108c28B7767a52BE38B4860832dd4e11A7ecad#code)
[KVStore on Moonbeam](https://moonbeam.moonscan.io/address/0x6617d21ab0f16A7079e2811Cf9306CAe7018bDd9#code)
[HMToken on Moonbeam](https://moonbeam.moonscan.io/address/0x3b25bc1dc591d24d60560d0135d6750a561d4764#contracts)

[Escrow Factory on Moonbase](https://moonbase.moonscan.io/address/0x3Cd0B117Be4CC1e31c8d7d1eD8b32208a2820902#code)
[KVStore on Moonbase](https://moonbase.moonscan.io/address/0x64009ca5fb4b34769F7240c6073FEc34bf5b64E3#code)
[HMToken on Moonbase](https://moonbase.moonscan.io/address/0xe4C8eC5d057EacF40060b2174627a4941a5c8127#code)
____________________________________________________________________________
**Task 5: Launch a working app on the network**

Relevant documentation is available [here](https://github.com/menezesphill/hmt-moonbeam#-fortune-dapp-example-video-on-moonbase). 
____________________________________________________________________________
**Task 6: Add to human dashboard**

PR [#24 on escrow-dashboard](https://github.com/humanprotocol/escrow-dashboard/pull/24) submitted for review
____________________________________________________________________________
**Task 7: Request to become the maintainer for your EVM network**

Please consider me to be the maintainer for Moonbeam! 😁
____________________________________________________________________________
**Task 8: Verify bridging of tokens works**

Relevant documentation is available [here](https://github.com/menezesphill/hmt-moonbeam#-cross-chain-swaps-on-multichain-network)
____________________________________________________________________________

Please let me know if anything is missing and/or needs rework.

best,
Phill

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 1.0 ETH (1810.73 USD @ $1810.73/ETH) has been submitted by__:

 1. [@menezesphill](https://gitcoin.co/menezesphill)



@human-protocol please take a look at the submitted work:
* [PR](https://github.com/humanprotocol/hmt-escrow/pull/326) by @menezesphill

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/28709)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/28709).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,769,654.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 1.0 ETH (1215.31 USD @ $1215.31/ETH)  attached to this issue has been approved & issued to @menezesphill.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/28709)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,309,655.68 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
