### ISSUE TITLE
Combine all of the package.json and yarn files

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/hmt-escrow#404]
The repo has a lot of examples, and different libraries which all have there own workflow. Let's combine into a single Docker/package.json file. The tests can be kept separate or combined at that point.

# Todo
- [ ] Remove all hard copies of abi and contract source code and replace them with some type of reusable logic
- [ ] Make sure python tests still run
- [ ] Reduce the number of docker containers and npm versions
- [ ] Closes https://github.com/humanprotocol/hmt-escrow/issues/390

**Comment by portuu3** [comment]
Done in monorepo
